export const ADD_CAPITAL = 'ADD_CAPITAL';
export const REMOVE_CAPITAL = 'REMOVE_CAPITAL';

export const FETCH_DISTANCE_MATRIX_START = 'FETCH_DISTANCE_MATRIX_START';
export const FETCH_DISTANCE_MATRIX_SUCCESS = 'FETCH_DISTANCE_MATRIX_SUCCESS';
export const FETCH_DISTANCE_MATRIX_FAIL = 'FETCH_DISTANCE_MATRIX_FAIL';

export const ANT_COLONY_OPTIMIZATION_START = 'ANT_COLONY_OPTIMIZATION_START';
export const ANT_COLONY_OPTIMIZATION_SUCCESS = 'ANT_COLONY_OPTIMIZATION_SUCCESS';

export const RESET_RESULTS_STATE = 'RESET_RESULTS_STATE';
export const RESET_CAPITALS_STATE = 'RESET_CAPITALS_STATE';